import org.calm4._
import Utils._
import CalmModel3._
import CalmImplicits._
import net.ruippeixotog.scalascraper.dsl.DSL.Extract._
import net.ruippeixotog.scalascraper.dsl.DSL._
import org.json4s._
import org.json4s.jackson.JsonMethods._
import org.json4s.JsonDSL._
